---
- name: Set Users
  user:
    name: '{{ item.name | default(item) }}'
    comment: '{{ item.comment | default(item.name) }}'
    groups: '{{ item.groups | default(omit) }}'
    shell: '{{ item.shell | default(wtd_users_default_shell) }}'
    home: '{{ item.home | default(wtd_users_default_home_path + item.name) }}'
    password: '{{ item.password_hash | default(wtd_users_default_password_hash) }}'
    update_password: '{{ item.update_password | default(wtd_users_default_password_update) }}'
    state: '{{ item.state | default(wtd_users_default_state) }}'
    move_home: yes
    remove: yes
  when: item.system | default(wtd_users_default_system) == "no"
  with_items:
    - '{{ wtd_users }}'
  tags:
    - users
    - groups

- name: Set System Users
  user:
    name: '{{ item.name | default(item) }}'
    comment: '{{ item.comment | default(item.name) }}'
    groups: '{{ item.groups | default(omit) }}'
    shell: '{{ item.shell | default(wtd_users_default_system_shell) }}'
    home: '{{ item.home | default(wtd_users_default_system_path + item.name) }}'
    password: '{{ item.password_hash | default(wtd_users_default_password_hash) }}'
    update_password: '{{ item.update_password | default(wtd_users_default_password_update) }}'
    state: '{{ item.state | default(wtd_users_default_state) }}'
    move_home: yes
    system: '{{ item.system | default(wtd_users_default_system) }}'
  when: item.system | default(wtd_users_default_system) == "yes"
  with_items:
    - '{{ wtd_users }}'
  tags:
    - users
    - groups
    - system

- name: Set authorized_keys
  authorized_key:
    user: "{{ item.name | default(item) }}"
    state: present
    key: "{{ lookup('file', item.keyfile) }}"
    exclusive: yes
    manage_dir: yes
  when: item.keyfile is defined
  with_items:
    - "{{ wtd_users }}"
  tags:
    - users
    - security

- name: Delete Users non declared authorized_keys
  file:
    path: "{{ item.home | default(wtd_users_default_home_path) + item.name | default(item) }}/{{ wtd_users_default_auth_key_path }}authorized_keys"
    state: absent
  when: (item.keyfile is not defined) and (item.system | default(wtd_users_default_system) == "no") and wtd_users_default_auth_key_exclusive
  with_items:
    - "{{ wtd_users }}"
  tags:
    - users
    - security

- name: Delete System Users non declared authorized_keys
  file:
    path: "{{ item.home | default(wtd_users_default_system_path) + item.name | default(item) }}/{{ wtd_users_default_auth_key_path }}authorized_keys"
    state: absent
  when: (item.keyfile is not defined) and (item.system | default(wtd_users_default_system) == "yes") and wtd_users_default_auth_key_exclusive
  with_items:
    - "{{ wtd_users }}"
  tags:
    - users
    - security
